import {products,money,total,validateOrder} from './domain.js';
const $=s=>document.querySelector(s);const key='dona-clara-v1';let state={cart:[],orders:[]};
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&Array.isArray(saved.orders)&&Array.isArray(saved.cart))state=saved;}catch{}
state.cart=state.cart.filter(l=>products.some(p=>p.id===l.id&&Number.isInteger(l.qty)&&l.qty>0&&l.qty<=p.stock));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const eventMinimum=()=>{const d=new Date();d.setDate(d.getDate()+2);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let timer;function toast(msg){$('#toast').textContent=msg;$('#toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,5500);}
function save(){try{localStorage.setItem(key,JSON.stringify(state));return true;}catch{toast('Não foi possível salvar neste navegador. Libere armazenamento para continuar.');return false;}}
function commit(next){const previous=state;state=next;if(!save()){state=previous;return false;}return true;}
let category='Todos';function renderProducts(){ $('#filters').innerHTML=['Todos','Pães','Doces','Coloniais'].map(c=>`<button class="${c===category?'active':''}" data-category="${c}" aria-pressed="${c===category}">${c}</button>`).join('');$('#products').innerHTML=products.filter(p=>category==='Todos'||p.category===category).map(p=>`<article class="card"><div class="productArt" aria-hidden="true"><span class="tag">${p.tag}</span><span class="glyph">${p.icon}</span></div><div class="cardBody"><h3>${p.name}</h3><p>${p.desc}</p><div class="buy"><div><b>${money(p.price)}</b><span class="stock">Limite por pedido: ${p.stock} un.</span></div><button data-add="${p.id}" aria-label="Adicionar ${p.name}">Adicionar +</button></div></div></article>`).join('');}
$('#filters').addEventListener('click',e=>{if(e.target.dataset.category){category=e.target.dataset.category;renderProducts();}});
$('#products').addEventListener('click',e=>{const id=e.target.dataset.add;if(!id)return;const cart=state.cart.map(l=>({...l}));let line=cart.find(l=>l.id===id);if(line&&line.qty>=products.find(p=>p.id===id).stock)return toast('Limite por pedido atingido.');if(line)line.qty++;else cart.push({id,qty:1});if(commit({...state,cart})){renderCart();toast('Adicionado à sua sacola.');}});
function renderCart(){ $('#count').textContent=state.cart.reduce((n,l)=>n+l.qty,0);$('#cartItems').innerHTML=state.cart.length?state.cart.map(l=>{const p=products.find(p=>p.id===l.id);return `<div class="cartLine"><div>${p.name}<br><b>${money(p.price*l.qty)}</b></div><div><button data-step="-1" data-id="${l.id}" aria-label="Diminuir quantidade de ${p.name}">−</button> ${l.qty} <button data-step="1" data-id="${l.id}" aria-label="Aumentar quantidade de ${p.name}">+</button></div></div>`;}).join(''):'<p class="empty">Sua sacola está esperando sua próxima fornada.</p>';$('#cartTotal').textContent='Total: '+money(total(state.cart));$('#checkout').hidden=!state.cart.length;$('#pickupDate').min=today();}
$('#cartItems').addEventListener('click',e=>{const {id,step}=e.target.dataset;if(!id)return;const cart=state.cart.map(l=>({...l}));const l=cart.find(l=>l.id===id);const qty=l.qty+Number(step);if(qty>products.find(p=>p.id===id).stock)return toast('Limite por pedido atingido.');l.qty=qty;if(commit({...state,cart:cart.filter(l=>l.qty>0)}))renderCart();});
$('#cartBtn').onclick=()=>{renderCart();$('#cartDialog').showModal();};$('#closeCart').onclick=()=>$('#cartDialog').close();
$('#checkout').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{validateOrder({...data,cart:state.cart},today());const order={id:crypto.randomUUID(),...data,kind:'Pedido',items:state.cart.map(l=>({...l,name:products.find(p=>p.id===l.id).name})),total:total(state.cart),status:'Recebido',createdAt:new Date().toISOString()};if(!commit({cart:[],orders:[order,...state.orders]}))return;e.target.reset();renderCart();renderPanel();$('#cartDialog').close();toast(`Pedido ${order.id.slice(0,8)} registrado neste navegador. Veja no painel demonstrativo.`);}catch(err){toast(err.message);}};
$('#eventDate').min=eventMinimum();$('#eventForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!/^\d{10,11}$/.test(data.phone.replace(/\D/g,'')))return toast('Informe telefone com DDD, com 10 ou 11 dígitos.');if(data.date<eventMinimum())return toast('Encomendas precisam de pelo menos 2 dias de antecedência.');if(!data.name.trim()||data.details.trim().length<10)return toast('Preencha nome e detalhes da encomenda.');const order={id:crypto.randomUUID(),...data,kind:'Encomenda',status:'Aguardando orçamento',createdAt:new Date().toISOString()};if(commit({...state,orders:[order,...state.orders]})){e.target.reset();renderPanel();toast('Solicitação registrada localmente. Orçamento pendente no painel.');}};
const stages=['Recebido','Em preparo','Pronto para retirada','Concluído','Cancelado'];const eventStages=['Aguardando orçamento','Confirmado','Em preparo','Pronto para retirada','Concluído','Cancelado'];
function renderPanel(){const active=state.orders.filter(o=>!['Concluído','Cancelado'].includes(o.status));$('#metrics').innerHTML=`<div class="metric">Pedidos em andamento<b>${active.filter(o=>o.kind==='Pedido').length}</b></div><div class="metric">Encomendas em andamento<b>${active.filter(o=>o.kind==='Encomenda').length}</b></div><div class="metric">Valor de pedidos ativos<b>${money(active.reduce((n,o)=>n+(o.total||0),0))}</b></div>`;$('#orders').innerHTML=state.orders.length?state.orders.map(o=>`<article class="order"><div class="sectionHead"><h3>${escape(o.name)}</h3><span class="badge">${escape(o.kind)} · #${escape(o.id.slice(0,8))}</span></div><p>Retirada / evento: <b>${escape(o.date.split('-').reverse().join('/'))} ${escape(o.time||'— horário nos detalhes')}</b><br>Telefone: ${escape(o.phone)}</p><p>${o.items?o.items.map(l=>`${escape(l.qty)} × ${escape(l.name)}`).join('<br>'):`${escape(o.type)}<br>${escape(o.details)}`}</p><p>${o.total?`Total: <b>${money(o.total)}</b>`:'Valor: orçamento pendente'}</p><label>Etapa do atendimento<select data-status="${escape(o.id)}">${(o.kind==='Pedido'?stages:eventStages).map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></label></article>`).join(''):'<div class="empty">Ainda não há pedidos. Faça um pedido ou solicite uma encomenda na loja para experimentar o fluxo.</div>';}
$('#orders').addEventListener('change',e=>{const id=e.target.dataset.status;if(!id)return;const order=state.orders.find(o=>o.id===id);if(!(order.kind==='Pedido'?stages:eventStages).includes(e.target.value))return;if(commit({...state,orders:state.orders.map(o=>o.id===id?{...o,status:e.target.value}:o)})){renderPanel();toast('Etapa atualizada.');}});
$('#panelBtn').onclick=()=>{$('#store').hidden=true;$('#panel').hidden=false;renderPanel();window.scrollTo(0,0);};$('#backBtn').onclick=()=>{$('#panel').hidden=true;$('#store').hidden=false;window.scrollTo(0,0);};
$('#exportBtn').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state.orders,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='dona-clara-pedidos.json';a.click();URL.revokeObjectURL(url);};
renderProducts();renderCart();renderPanel();
